### ISSUE TITLE
Gen golang protobufs

### ISSUE THREAD

**Issue by winwisely99** [bayard-search/bayard-proto#1]
We would like to experiment with Bayard from golang and dart.

We are wanted to build a flutter GUI on top of Bayard focussed on doing faceted search which is highly useful for our project.

https://github.com/getcouragenow

I think we would also put in a golang layer to hook up NATS into Bayard so it's events can be published to NATS but also so it can store and index documents from other systems 

It's looks much better than blast. Really amazing work !

Could you add the required code to the proto.sh  for golang code gen ?
I can do the same for Dart.

**Comment by mosuka** [comment]
Hi  @winwisely99 ,
Sounds great! But currently, I am working on making Bayard more stable.
Can you send me a pull request if you are in a hurry?

**Comment by mosuka** [comment]
Hi @winwisely99 ,
I added a script for generating golang code.
https://github.com/bayard-search/bayard-proto/blob/master/protoc_go.sh

And I also committed the golang code that generated.
https://github.com/bayard-search/bayard-proto/tree/master/go/pkg/proto

Please check it out when you have time.
Thanks!
